services:
  app:
    build: .
    container_name: wesee_app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  studio:
    image: node:20-slim
    container_name: realest
    working_dir: /app/studio
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    # Svarbu: SANITY_AUTH_TOKEN leid≈æia konteineriui veikti be login
    environment:
      - SANITY_AUTH_TOKEN=skY29PG3XjOXqx3SQHIo8t1571iix6QSSOElVyhgpzmKkVP0np6riOm6cZNeNKQXe4mAoc8HaB7qgEApbq0xqB70GgjLKQqxvOIPsoxQxhmzIUrlYVaXw7IMpJeF7YG7YKcVNSY021Zdu2H5kra0i1jSrEEAKVDvhAo3Y9dvAtKT6TnjWuA3 
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"